### ISSUE TITLE
API getCollections returns response code: 500, message: Internal Server Error

### ISSUE THREAD

**Issue by shanghaiyangming** [flanker/chromadb-admin#7]
![image](https://github.com/user-attachments/assets/5961a1fc-51e5-48c4-813f-d630a7cf063f)

Something went wrong
API getCollections returns response code: 500, message: Internal Server Error

Go to [Setup](http://localhost:3001/setup).

**Comment by jarildson** [comment]
can confirm, also getting this error.

**Comment by jarildson** [comment]
`> chromadb-admin@0.1.0 start
> next start

  ▲ Next.js 14.2.3
  - Local:        http://localhost:3000

 ✓ Starting...
 ✓ Ready in 203ms
An unexpected error occurred: TypeError: fetch failed
    at node:internal/deps/undici/undici:13185:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async J.listCollections (/app/.next/server/chunks/322.js:12:76536)
    at async o (/app/.next/server/app/api/collections/route.js:1:2283)
    at async c (/app/.next/server/app/api/collections/route.js:1:1236)
    at async /app/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:34666
    at async eS.execute (/app/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:25813)
    at async eS.handle (/app/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:35920)
    at async doRender (/app/node_modules/next/dist/server/base-server.js:1377:42)
    at async cacheEntry.responseCache.get.routeKind (/app/node_modules/next/dist/server/base-server.js:1599:28) {
  [cause]: Error: connect ECONNREFUSED 127.0.0.1:8000
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 8000
  }
}
 ⨯ TypeError: fetch failed
    at node:internal/deps/undici/undici:13185:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async J.listCollections (/app/.next/server/chunks/322.js:12:76536)
    at async o (/app/.next/server/app/api/collections/route.js:1:2283)
    at async c (/app/.next/server/app/api/collections/route.js:1:1236)
    at async /app/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:34666
    at async eS.execute (/app/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:25813)
    at async eS.handle (/app/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:35920)
    at async doRender (/app/node_modules/next/dist/server/base-server.js:1377:42)
    at async cacheEntry.responseCache.get.routeKind (/app/node_modules/next/dist/server/base-server.js:1599:28) {
  [cause]: Error: connect ECONNREFUSED 127.0.0.1:8000
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 8000
  }
}
An unexpected error occurred: TypeError: fetch failed
    at node:internal/deps/undici/undici:13185:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async J.listCollections (/app/.next/server/chunks/322.js:12:76536)
    at async o (/app/.next/server/app/api/collections/route.js:1:2283)
    at async c (/app/.next/server/app/api/collections/route.js:1:1236)
    at async /app/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:34666
    at async eS.execute (/app/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:25813)
    at async eS.handle (/app/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:35920)
    at async doRender (/app/node_modules/next/dist/server/base-server.js:1377:42)
    at async cacheEntry.responseCache.get.routeKind (/app/node_modules/next/dist/server/base-server.js:1599:28) {
  [cause]: Error: connect ECONNREFUSED 127.0.0.1:8000
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 8000
  }
}
 ⨯ TypeError: fetch failed
    at node:internal/deps/undici/undici:13185:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async J.listCollections (/app/.next/server/chunks/322.js:12:76536)
    at async o (/app/.next/server/app/api/collections/route.js:1:2283)
    at async c (/app/.next/server/app/api/collections/route.js:1:1236)
    at async /app/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:34666
    at async eS.execute (/app/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:25813)
    at async eS.handle (/app/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:35920)
    at async doRender (/app/node_modules/next/dist/server/base-server.js:1377:42)
    at async cacheEntry.responseCache.get.routeKind (/app/node_modules/next/dist/server/base-server.js:1599:28) {
  [cause]: Error: connect ECONNREFUSED 127.0.0.1:8000
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 8000
  }
}`

**Comment by jarildson** [comment]
Ahh, I figured it out. Setting it to localhost didn't work. Setting instead to the hostname of the server worked fine.

**Comment by vipinazad-85** [comment]
I am also facing the same issue, tried both localhost and 127.0.0.1 not luck.

can i get any insight what could be wrong ?

**Comment by flanker** [comment]
I just migrated to v2 API in the latest commit. please have a try and let me know if there is any issue. cheers.

**Comment by vipinazad-85** [comment]
why it is hard coded to use "http://host.docker.internal:8000" string ?

**Comment by rsrini7** [comment]
same but, in log its showing as "GET /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 400

tried http://localhost:8000, and docker compose service name http://chroma:8000 and then "http://host.docker.internal:8000/"

All behave same with above 400 error without details

**Comment by flanker** [comment]
@rsrini7 @vipinazad-85 could you tell me which version of ChromaDB you're running? Are you deploying it locally using Docker? Cheers.

**Comment by pankaj9296** [comment]
looks like docker image is not up t date and throwing this error?

**Comment by rsrini7** [comment]
both docker and local mode http / client.

The issue suspecting the new version v2 http://localhost:8000/api/v2/heartbeat

Docker image: chromadb/chroma:1.0.5
----

chroma run .\chroma-config.yaml

chroma-config.yml

port: 8000
listen_address: "0.0.0.0"
max_payload_size_bytes: 41943040
# cors_allow_origins: ["*"]
persist_path: "./backend/data/chroma"
allow_reset: false # defaults to false
telemetry: false
anonymized_telemetry: false
sqlitedb:
  hash_type: "md5" # or "sha256"
  migration_mode: "apply" # or "validate"
sysdb:
  sqlite:
    log_topic_namespace: "default"
    log_tenant: "default"

**Comment by jccbbb** [comment]
Also get the same error.
